Matjin/add race condition
matjin/infersharp pull request #3
Opened 2021-09-13 22:31 UTC by matjin

Provides support for thread-safety violation detection.

Tested:
Added unit test case.

2021-09-16 17:54 UTC, xi-liu-ds commented
We might want to include the following change in `run_infersharp.sh` at line 26:

```suggestion
sudo infer $(infer help --list-issue-types 2> /dev/null | grep ':true:' | cut -d ':' -f 1 | sed -e 's/^/--disable-issue-type /') --enable-issue-type NULL_DEREFERENCE --enable-issue-type DOTNET_RESOURCE_LEAK --enable-issue-type THREAD_SAFETY_VIOLATION analyzejson --debug --cfg-json $1/cfg.json --tenv-json $1/tenv.json
```

2021-09-16 17:56 UTC, xi-liu-ds requested changes
We might want to include the following change in `run_infersharp.sh` at line 26:

```suggestion
sudo infer $(infer help --list-issue-types 2> /dev/null | grep ':true:' | cut -d ':' -f 1 | sed -e 's/^/--disable-issue-type /') --enable-issue-type NULL_DEREFERENCE --enable-issue-type DOTNET_RESOURCE_LEAK --enable-issue-type THREAD_SAFETY_VIOLATION analyzejson --debug --cfg-json $1/cfg.json --tenv-json $1/tenv.json
```

2021-10-08 00:59 UTC, matjin commented
> We might want to include the following change in `run_infersharp.sh` at line 26:
> 
> ```
> sudo infer $(infer help --list-issue-types 2> /dev/null | grep ':true:' | cut -d ':' -f 1 | sed -e 's/^/--disable-issue-type /') --enable-issue-type NULL_DEREFERENCE --enable-issue-type DOTNET_RESOURCE_LEAK --enable-issue-type THREAD_SAFETY_VIOLATION analyzejson --debug --cfg-json $1/cfg.json --tenv-json $1/tenv.json
> ```

Done.

2021-10-08 20:27 UTC, xi-liu-ds approved these changes

2021-10-08 21:03 UTC, merged